version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: pwalsh/emacs:0.0.2
    steps:
      - checkout
      - run:
          name: Create a test project
          command: mkdir existing-project && cd existing-project && pipenv --python 2 && cd ../
      - run:
          name: Install test dependencies
          command: make install
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test
